# Copyright 2026 TIER IV, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Write the nuScenes dataset record table.

T4dataset tables are generated by t4dataset-generator. nuScenes has no external
generator, so its table is written here, into a plain parquet file named by the config
and shared by every model that trains on it.
"""

import logging

import hydra
from hydra.utils import instantiate
from omegaconf import DictConfig, OmegaConf

from autoware_ml.configs.paths import CONFIGS_ROOT
from autoware_ml.configs.resolvers import register_config_resolvers

logger = logging.getLogger(__name__)
register_config_resolvers()
_CONFIG_PATH = str(CONFIGS_ROOT / "writers")


@hydra.main(version_base=None, config_path=_CONFIG_PATH)
def main(cfg: DictConfig):
    """
    Write the dataset record table of the configured nuScenes version.

    Args:
        cfg: Hydra configuration
    """
    logger.info(f"Configuration:\n{OmegaConf.to_yaml(cfg)}")
    writer = instantiate(cfg.writer)
    logger.info(f"Writer: {writer}")
    out_file = writer.write()
    logger.info(f"Record table written to {out_file}")


if __name__ == "__main__":
    main()
