hydra:
  run:
    dir: ${log_output_dir}
  output_subdir: code/hydra
  searchpath:
    - pkg://autoware_ml.configs

defaults:
  - override hydra/hydra_logging: none
  - nuscenes/labels@writer.class_names: detection3d/default_class_names
  - nuscenes/labels@writer.label_remapper: detection3d/default_label_remapper
  - nuscenes/box3d_pipelines@writer.box3d_pipelines: default_box3d_pipelines
  - nuscenes/scenarios@writer.scenarios.trainval: trainval
  - _self_

date_format: "%Y.%m.%d.%H.%M.%S"
experiment_uid: ${now:${date_format}}
log_output_dir: outputs/records/${experiment_uid}

data_root_path: ${oc.env:AUTOWARE_ML_DATA_PATH}

writer:
  _target_: autoware_ml.databases.nuscenes.nuscenes_records_writer.NuscenesRecordsWriter
  _convert_: all

  nuscenes_version: v1.0-trainval
  root_path: ${data_root_path}/nuscenes/
  out_file: /workspace/records/nuscenes.parquet

  lidar_pointcloud_num_features: 5
  num_workers: 8
  ignore_label_index: -1
