_target_: autoware_ml.datamodule.t4dataset.dataset.T4Dataset
_convert_: all

defaults:
  - segmentation3d@dataset_tasks.Segmentation3D: default_segmentation3d
  - ../../transforms@transforms: default_segmentation3d_train_transforms

database_root_path: ${database.root_path}

# Always None since we run splitter in the process
dataset_records_dataframe: null

# 3D segmentation carries no bboxes, so no padding is needed
max_num_3d_gt_bboxes: 0
