# @package _global_
defaults:
  - /tasks/segmentation3d/ptv3/tiny
  - /datasets/t4dataset/detection3d
  - /datasets/t4dataset/segmentation3d
  - /datasets/t4dataset/lidar
  - /database@database: t4dataset/t4dataset_j6gen2_semaseg
  - _self_

dataset: ${t4dataset}

batch_size: 16
num_workers: 8

grid_size: 0.12
max_voxels: 524288
point_cloud_range: [-122.88, -122.88, -3.0, 122.88, 122.88, 5.0]

datamodule:
  dataset:
    _target_: autoware_ml.datamodule.t4dataset.dataset.T4Dataset
    _partial_: true
  train_sources:
    - database: ${database}
      det3d: false
      seg3d: true
      repeat: 1
  val_sources: ${datamodule.train_sources}
  test_sources: ${datamodule.train_sources}
  train_dataloader_cfg:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  val_dataloader_cfg:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader_cfg:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  train_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.point_cloud.sweeps.LoadPointsFromMultiSweeps
        sweeps_num: 2
        use_features: [x, y, z, intensity, timestamp_difference]
        remove_close: true
        sweep_selection: random
        time_lag_range: [0.05, 0.25]
      - _target_: autoware_ml.transforms.segmentation3d.loading.LoadSeg3DAnnotations
        taxonomy: ${database.taxonomy.segmentation3d}
      - _target_: autoware_ml.transforms.point_cloud.formatting.PreparePointCloudInput
        require_time_lag: true
      - _target_: autoware_ml.transforms.segmentation3d.formatting.PreparePointSegInput
        ignore_index: ${dataset.segmentation3d.ignore_index}
        require_labels: true
      - _target_: autoware_ml.transforms.point_cloud.geometry.RandomRotateTargetAngle
        p: 0.75
        angle: [0.5, 1.0, 1.5]
        center: [0.0, 0.0, 0.0]
      - _target_: autoware_ml.transforms.point_cloud.geometry.GlobalRotScaleTrans
        rot_range: [-3.14159, 3.14159]
        scale_ratio_range: [0.9, 1.1]
        translation_std: [0.5, 0.5, 0.2]
      - _target_: autoware_ml.transforms.point_cloud.geometry.RandomFlip3D
        flip_ratio_bev_horizontal: 0.5
        flip_ratio_bev_vertical: 0.5
      - _target_: autoware_ml.transforms.point_cloud.perturbation.RandomJitter
        sigma: 0.012
        clip: 0.05
      - _target_: autoware_ml.transforms.point_cloud.crop.PointsRangeFilter
        point_cloud_range: ${point_cloud_range}
      - _target_: autoware_ml.transforms.point_cloud.sampling.RandomDropout
        p: 0.5
        dropout_ratio: 0.2
      - _target_: autoware_ml.transforms.point_cloud.perturbation.RandomStrengthJitter
        gamma_range: [0.8, 1.25]
        scale_range: [0.9, 1.1]
        shift_range: [-0.02, 0.02]
      - _target_: autoware_ml.transforms.common.packing.BuildPointFeatures
        feature_names: [x, y, z, intensity, timestamp_difference]
  val_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.point_cloud.sweeps.LoadPointsFromMultiSweeps
        sweeps_num: 2
        use_features: [x, y, z, intensity, timestamp_difference]
        remove_close: true
        sweep_selection: nearest
        time_lag_range: [0.05, 0.25]
      - _target_: autoware_ml.transforms.segmentation3d.loading.LoadSeg3DAnnotations
        taxonomy: ${database.taxonomy.segmentation3d}
      - _target_: autoware_ml.transforms.point_cloud.formatting.PreparePointCloudInput
        require_time_lag: true
      - _target_: autoware_ml.transforms.segmentation3d.formatting.PreparePointSegInput
        ignore_index: ${dataset.segmentation3d.ignore_index}
        require_labels: true
      - _target_: autoware_ml.transforms.point_cloud.crop.PointsRangeFilter
        point_cloud_range: ${point_cloud_range}
      - _target_: autoware_ml.transforms.common.packing.BuildPointFeatures
        feature_names: [x, y, z, intensity, timestamp_difference]
  test_transforms: ${datamodule.val_transforms}
  predict_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.point_cloud.sweeps.LoadPointsFromMultiSweeps
        sweeps_num: 2
        use_features: [x, y, z, intensity, timestamp_difference]
        remove_close: true
        sweep_selection: nearest
        time_lag_range: [0.05, 0.25]
      - _target_: autoware_ml.transforms.point_cloud.formatting.PreparePointCloudInput
        require_time_lag: true
      - _target_: autoware_ml.transforms.segmentation3d.formatting.PreparePointSegInput
        ignore_index: ${dataset.segmentation3d.ignore_index}
        require_labels: false
      - _target_: autoware_ml.transforms.point_cloud.crop.PointsRangeFilter
        point_cloud_range: ${point_cloud_range}
      - _target_: autoware_ml.transforms.common.packing.BuildPointFeatures
        feature_names: [x, y, z, intensity, timestamp_difference]
