# @package _global_
defaults:
  - /tasks/calibration_status/calibration_status_classifier/resnet18_base
  - /datasets/nuscenes/detection3d
  - /datasets/nuscenes/camera
  - /database@database: nuscenes/nuscenes_trainval
  - _self_

dataset: ${nuscenes}

datamodule:
  dataset:
    _target_: autoware_ml.datamodule.nuscenes.dataset.NuscenesDataset
    _partial_: true
    calibration_cameras: ${dataset.camera.camera_order}
  train_sources:
    - database: ${database}
      det3d: false
      seg3d: false
      repeat: 1
  val_sources: ${datamodule.train_sources}
  test_sources: ${datamodule.train_sources}
