# @package _global_
defaults:
  - /tasks/calibration_status/calibration_status_classifier/resnet18_base
  - /datasets/nuscenes/camera
  - /records@records: nuscenes/nuscenes_trainval
  - _self_

dataset: ${nuscenes}

datamodule:
  dataset:
    _target_: autoware_ml.datamodule.nuscenes.dataset.NuscenesDataset
    _partial_: true
    calibration_cameras: ${dataset.camera.camera_order}
  sources:
    - records: ${records}
      det3d: false
      seg3d: false
      repeat: 1
