# @package _global_
defaults:
  - /tasks/calibration_status/calibration_status_classifier/resnet18_base
  - /datasets/t4dataset/detection3d
  - /datasets/t4dataset/camera
  - /database@database: t4dataset/t4dataset_gen2_base
  - _self_

dataset: ${t4dataset}

datamodule:
  dataset:
    _target_: autoware_ml.datamodule.t4dataset.dataset.T4Dataset
    _partial_: true
    calibration_cameras: ${dataset.camera.camera_order}
  train_sources:
    - database: ${database}
      det3d: false
      seg3d: false
      repeat: 1
  val_sources: ${datamodule.train_sources}
  test_sources: ${datamodule.train_sources}
