# @package _global_

defaults:
  - /datamodule/splitter@datamodule.splitter: default_scenario_splitter

datamodule:
  _target_: autoware_ml.datamodule.base.DataModule
  _convert_: all
  dataset: ???
  train_sources: ???
  val_sources: ???
  test_sources: ???
  train_dataloader_cfg:
    pin_memory: true
    persistent_workers: true
    drop_last: false
    shuffle: false
  val_dataloader_cfg:
    pin_memory: true
    persistent_workers: true
    drop_last: false
    shuffle: false
  test_dataloader_cfg:
    pin_memory: true
    persistent_workers: true
    drop_last: false
    shuffle: false
  predict_dataloader_cfg:
    pin_memory: true
    persistent_workers: true
    drop_last: false
    shuffle: false
  train_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
  val_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
  test_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
  predict_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
